server:
  port: 8081

spring:
  application:
    name: pocs

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    properties:
      acks: all
      retries: 3
  # Configura��o AWS LocalStack
aws:
  s3:
    endpoint: http://localhost:4566/
    region: us-east-1
    bucket-name: csv-bucket
    access-key: test
    secret-key: test

# Configura��o Kafka
kafka:
  topic:
    csv-data: pessoas-topic

# Configura��o de processamento
csv:
  processing:
    batch-size: 100


